---
title: "Analysis of BiPOCD data"
author: "Sebastian Sauer"
date: "4 Juli 2016"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

library(dplyr)
library(ggplot2)
library(tidyr)
library(readr)
library(stringr)
library(ggvis)
library(pander)
library(purrr)
library(caret)


# define paths
path_data <- "~/Documents/OneDrive/Forschung/Online_Behavior_Therapy/raw_data"
path_file_data <- "~/Documents/OneDrive/Forschung/Online_Behavior_Therapy/raw_data/BiPOCD prediction.csv"
path_code <- "~/Documents/OneDrive/Forschung/Online_Behavior_Therapy/R_code"
path_figs <- "~/Documents/OneDrive/Forschung/Online_Behavior_Therapy/Figures"
path_obj <- "~/Documents/OneDrive/Forschung/Online_Behavior_Therapy/data_objects"

# load data
data <- read_csv(path_file_data)


# constants
red1 <- "#880011"
```

# First glimpse

```{r}
glimpse(data)
```


##  Variable names
The main (raw) data file has a dimension of `r dim(data)` (rows*cols). The col names are:

```{r}
names(data)
```


## Summaries of variables

```{r}
data %>% 
  do(summary_num = summary(.)) -> sums
sums$summary_num


data %>% 
  select_if(is.numeric) %>% 
  ncol  # number of numeric variables


data %>% 
  select_if(negate(is.numeric)) %>% 
  ncol  # number of non-numeric variables

```


## Histograms of quantitative variables

```{r histograms_numeric, cache = TRUE}
data %>% 
  select_if(is.numeric) %>% 
  gather(key = variable, value = value) %>% 
  ggplot(aes(x = value)) + 
  geom_histogram() + 
  facet_wrap(~variable, scales = "free", ncol = 10)

```


## Histogram of non-numeric variables

```{r, cache = TRUE}
data %>% 
  select_if(negate(is.numeric)) %>%
  do(qplot(data = .))
  
```


## Check for (Near) Zero variables

```{r}
data %>% 
  select(-ID) %>% 
  select_if(is.numeric) %>% 
  nearZeroVar(., saveMetrics = TRUE) %>% 
  pander
```

